version: '3.3'
services:
  elasticsearch-viz-enabler:
    container_name: elasticsearch-viz-enabler
    image: elasticsearch:6.7.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "cluster.name=elasticsearch"