apiVersion: apps/v1beta2
kind: Deployment
metadata:
    name: {{ template "thischart.fullname" . }}
    namespace: {{ .Values.namespace }}
spec:
    replicas: 1
    selector:
        matchLabels:
            app: {{ template "thischart.name" . }}
            release: {{ .Release.Name }}
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 0
            maxSurge: 1
    template:
        metadata:
            labels:
                app: {{ template "thischart.name" . }}
                release: {{ .Release.Name }}
        spec:
            containers:
                - name: discovery-srv
                  image: "ubirch/viz-enabler-server:{{ .Values.image.tag | default "latest" }}"
                  imagePullPolicy: Always
                  ports:
                      - containerPort: {{ .Values.webuiapi.server.port }}
                      - containerPort: 9010
                  resources:
                      requests:
                          cpu: 0.5
                          memory: 0.3Gi
                      limits:
                          cpu: 1
                          memory: 0.5Gi
                  readinessProbe:
                      tcpSocket:
                          port: 9010
                      initialDelaySeconds: 10
                      periodSeconds: 10
                  livenessProbe:
                      tcpSocket:
                          port: 9010
                      initialDelaySeconds: 20
                      periodSeconds: 60
                  env:

                      - name: API_ENV_SERV_PORT
                        value: {{ .Values.webuiapi.server.port | quote }}
                      - name: API_ENV_SERV_URL
                        value: {{ .Values.webuiapi.server.baseUrl | quote }}
                      - name: API_ENV_SERV_SCALATRA_ENV
                        value: {{ .Values.webuiapi.server.scalatra.environment | quote }}
                      - name: API_ENV_SERV_SWAGGERPATH
                        value: {{ .Values.webuiapi.server.swaggerPath | quote }}
                      - name: API_ENV_APP_VERSION
                        value: {{ .Values.webuiapi.app.version | quote }}
                      - name: VIZ_ENABLER_ENV_METRICS_ES_PROTOCOL
                        value: "{{ .Values.elasticsearch.protocol }}"
                      - name: VIZ_ENABLER_ENV_METRICS_ES_HOST
                        value: "{{ .Values.elasticsearch.host }}"
                      - name: VIZ_ENABLER_ENV_METRICS_ES_PORT
                        value: "{{ .Values.elasticsearch.port }}"
                      - name: VIZ_ENABLER_ENV_METRICS_ES_IO_USER
                        valueFrom:
                          secretKeyRef:
                            name: "elastico-secrets"
                            key: "ELASTIC_IO_USER"
                      - name: VIZ_ENABLER_ENV_METRICS_ES_PASSWORD
                        valueFrom:
                          secretKeyRef:
                            name: "elastico-secrets"
                            key: " ELASTIC_IO_PASSWORD"
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            terminationGracePeriodSeconds: 30
{{- with .Values.imagePullSecrets }}
            imagePullSecrets:
{{ toYaml . | indent 14 }}
{{end}}
